---

# Default Ansible user
# change this if you use a non-root user for running Ansible playbooks
ansible_system_user: root

# EPEL Repository for extra packages
epel_repo: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

##########
## Subnet for Env and Domain, pass env as extra variable to playbook run command
#########
subnet: nnn 
domain: localdomain
env: prod
###
## Provide IP address only for master node for sentinel configuration
##
data_dir: /data/pg
admin_password: inputpasswordhere
pgpool_password: inputpasswordhere
repmgr_password: inputpasswordhere
###in form of xx.xx.xx.xx/xx
node1_ip: xx.xx.xx.xx/xx
node2_ip: xx.xx.xx.xx/xx
pgpool_ip1: xx.xx.xx.xx/xx
pgpool_ip2: xx.xx.xx.xx/xx
master_node: prodpsql01.localdomain
slave_node: prodpsql02.localdomain
pgpool_node1: prodpool01.localdomain
pgpool_node2: prodpool02.localdomain
vipaddress: xx.xx.xx.xx
ethdevice: eth01
vipname: psqlvip.localdomain

